{
    "name": "School Management",
    "version": "16.0.1.0.0",
    "summary": "Full school management: students, teachers, classes, attendance, grades, fees.",
    "author": "Zayed",
    "category": "Education",
    "depends": ["base", "mail", "web_responsive", "base_user_role"],
    "icon": "/school_management/static/description/icon.svg",
    "data": [
        "security/groups.xml",
        "security/student_rules.xml",
        "security/ir.model.access.csv",
        "data/sequences.xml",
        "views/school_info_views.xml",
        "views/teacher_views.xml",
        "views/student_views.xml",
        "views/admission_views.xml",
        "views/section_views.xml",
        "views/submission_views.xml",
        "views/assignment_views.xml",
        "views/class_views.xml",
        "views/course_views.xml",
        "views/classroom_views.xml",
        "views/academic_year_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
